# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Some_value', max_length=1000),
        ),
    ]
